/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MeetingService } from "../meeting.service";
import { MeetingCreateInput } from "./MeetingCreateInput";
import { Meeting } from "./Meeting";
import { MeetingFindManyArgs } from "./MeetingFindManyArgs";
import { MeetingWhereUniqueInput } from "./MeetingWhereUniqueInput";
import { MeetingUpdateInput } from "./MeetingUpdateInput";

export class MeetingControllerBase {
  constructor(protected readonly service: MeetingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Meeting })
  async createMeeting(
    @common.Body() data: MeetingCreateInput
  ): Promise<Meeting> {
    return await this.service.createMeeting({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Meeting] })
  @ApiNestedQuery(MeetingFindManyArgs)
  async meetings(@common.Req() request: Request): Promise<Meeting[]> {
    const args = plainToClass(MeetingFindManyArgs, request.query);
    return this.service.meetings({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Meeting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async meeting(
    @common.Param() params: MeetingWhereUniqueInput
  ): Promise<Meeting | null> {
    const result = await this.service.meeting({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Meeting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMeeting(
    @common.Param() params: MeetingWhereUniqueInput,
    @common.Body() data: MeetingUpdateInput
  ): Promise<Meeting | null> {
    try {
      return await this.service.updateMeeting({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Meeting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMeeting(
    @common.Param() params: MeetingWhereUniqueInput
  ): Promise<Meeting | null> {
    try {
      return await this.service.deleteMeeting({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
