/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Expense } from "./Expense";
import { ExpenseCountArgs } from "./ExpenseCountArgs";
import { ExpenseFindManyArgs } from "./ExpenseFindManyArgs";
import { ExpenseFindUniqueArgs } from "./ExpenseFindUniqueArgs";
import { CreateExpenseArgs } from "./CreateExpenseArgs";
import { UpdateExpenseArgs } from "./UpdateExpenseArgs";
import { DeleteExpenseArgs } from "./DeleteExpenseArgs";
import { ExpenseService } from "../expense.service";
@graphql.Resolver(() => Expense)
export class ExpenseResolverBase {
  constructor(protected readonly service: ExpenseService) {}

  async _expensesMeta(
    @graphql.Args() args: ExpenseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Expense])
  async expenses(
    @graphql.Args() args: ExpenseFindManyArgs
  ): Promise<Expense[]> {
    return this.service.expenses(args);
  }

  @graphql.Query(() => Expense, { nullable: true })
  async expense(
    @graphql.Args() args: ExpenseFindUniqueArgs
  ): Promise<Expense | null> {
    const result = await this.service.expense(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Expense)
  async createExpense(
    @graphql.Args() args: CreateExpenseArgs
  ): Promise<Expense> {
    return await this.service.createExpense({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Expense)
  async updateExpense(
    @graphql.Args() args: UpdateExpenseArgs
  ): Promise<Expense | null> {
    try {
      return await this.service.updateExpense({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Expense)
  async deleteExpense(
    @graphql.Args() args: DeleteExpenseArgs
  ): Promise<Expense | null> {
    try {
      return await this.service.deleteExpense(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
